# URL to download the CSV file
csvURL: "https://randomurl.com/whitelist.csv"

# Refresh time, in seconds
syncTime: 60

# Servers the plugin will give join permission for
servers:
- "survie"
- "skyblock"